[workspace]
resolver = "3"
members = ["cards", "poker-cards"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
mutants = "0.0.4"
thiserror = "2.0.20"

[workspace.lints.clippy]
arithmetic_side_effects = "deny"
as_conversions = "deny"
clone_on_copy = "deny"
exit = "deny"
expect_used = "deny"
indexing_slicing = "deny"
map_entry = "deny"
needless_borrow = "deny"
nursery = { level = "deny", priority = -1 }
panic = "deny"
panic_in_result_fn = "deny"
pedantic = { level = "deny", priority = -1 }
redundant_closure = "deny"
redundant_closure_for_method_calls = "deny"
string_slice = "deny"
todo = "deny"
type_complexity = "deny"
unchecked_time_subtraction = "deny"
unimplemented = "deny"
unreachable = "deny"
unwrap_used = "deny"
