name: Test and lint

on:
    push:
    workflow_dispatch:
    workflow_call:

jobs:
    test-lint:
        name: Test and lint
        runs-on: ubuntu-latest
        env:
            RUSTFLAGS: "-Dwarnings"
        steps:
            - uses: actions/checkout@v6
            - uses: taiki-e/install-action@v2
              with:
                  tool: |
                      rust+clippy
                      rust@nightly+rustfmt
                      nextest
                      cargo-mutants
                      cargo-llvm-cov
            - run: cargo +nightly fmt --all --check
            - run: cargo clippy --all-targets --all-features -- -Dwarnings -Dclippy::all
            - run: cargo llvm-cov nextest run --all-targets --all-features --no-fail-fast
            - run: cargo mutants --in-place --test-tool=nextest
